name: kaggle_santa2022
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7.12
  - numpy=1.21.6
  - pandas=1.3.5
  - pip=21.1.2
  - tqdm=4.64.0
  - pytorch=1.11.0
  - black=22.6.0
  - kaggle=1.5.12
  - scikit-learn=1.0.2
  - ipykernel=6.15.0
  - wandb=0.12.21
  - matplotlib=3.5.3
  - pip:
    - pygame==2.1.2
    - gym==0.26.2
    - moviepy==1.0.3