name: aimo2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black
  - datasets=3.1.0
  - kaggle=1.6.17
  - ipykernel=6.29.4
  - matplotlib
  - numpy=1.26.4
  - pandas=2.2.3
  - pip=24.0
  - polars=1.9.0
  - python=3.10.14
  - pytest=8.3.3
  - pytorch=2.4.0
  - scikit-learn=1.2.2
  - sentencepiece=0.2.0
  - tensorboard=2.16.2
  - tqdm=4.66.6
  - transformers=4.46.1
  - tokenizers=0.20.1
  - wandb
  - pip:
    - vllm==0.6.3.post1