name: kaggle_feedback2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.12
  - numpy
  - pip
  - tensorboard=2.8.0
  - tqdm
  - pytorch=1.10.0
  - black
  - transformers
  - datasets
  - tokenizers
  - kaggle
  - scikit-learn
  - ipykernel
  - wandb